version: '3.8'

services:
  docker-server-clswk: 
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://cats-db-clswk:5432/cats_db_clswk
    depends_on:
      - cats-db-clswk
  cats-db-clswk: 
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=cats_db_clswk
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
